# Generated by Django 5.2.13 on 2026-04-25 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('weight_kg', models.FloatField()),
                ('height_cm', models.FloatField()),
                ('goal', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=50)),
                ('days_available', models.IntegerField()),
                ('equipment', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FitnessProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=255)),
                ('duration_weeks', models.IntegerField()),
                ('daily_calories', models.IntegerField()),
                ('proteins_grams', models.IntegerField()),
                ('carbs_grams', models.IntegerField()),
                ('fats_grams', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='api.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=50)),
                ('target_muscles', models.CharField(max_length=100)),
                ('fitness_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_days', to='api.fitnessprogram')),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sets', models.IntegerField()),
                ('reps', models.CharField(max_length=50)),
                ('rest_seconds', models.IntegerField()),
                ('workout_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='api.workoutday')),
            ],
        ),
    ]
