# Generated by Django 6.0.4 on 2026-04-28 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_exercise_id_alter_fitnessprogram_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
